# Set prefix key
set -g prefix 'C-\'
bind 'C-\' send-prefix
unbind C-b

# Reload tmux config
bind r source-file $TMUX_CONFIG \; display "Tmux config loaded!"

# Use vim keybindings
setw -g mode-keys vi

# Move around Tmux split with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Color for active panel
set-option -g pane-border-style fg="#BE0029"
