# Keymaps

# VIM BINDS

## Use 'v' to begin selection like in Vim
#bind-key -T copy-mode-vi v send-keys -X begin-selection

## Use 'y' to yank selected text (copy to clipboard)
#bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -sel clip -i"

## Use 'p' to paste from clipboard
#bind p paste-buffer

## Use 'h', 'j', 'k', 'l' for pane movement
#bind -n M-h select-pane -L
#bind -n M-j select-pane -D
bind -n M-j select-pane -t :.+
#bind -n M-k select-pane -U
bind -n M-k select-pane -t :.-
#bind -n M-l select-pane -R

# NAVIGATION

# SWITCH WINDOWS WITHOUT PREFIX USING ALT
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 0

# ALT + H/L SWITCHES WINDOWS
bind -n M-p previous-window
bind -n M-n next-window

# Moving window
bind -n M-H swap-window -t -1
bind -n M-L swap-window -t +1

# RENAMING

unbind w
bind-key w command-prompt -p "Rename window to: " "rename-window '%%'"
unbind s
bind-key s command-prompt -p "Rename session to: " "rename-session '%%'"

# CLOSING

bind -n M-d detach-client
bind -n M-q kill-pane
bind -n M-x kill-window
bind -n M-Q kill-session

# NEW PANES/WINDOWS

# New window
bind -n M-c new-window
# Split vertically, new pane on the right
bind -n M-v split-window -v -c "#{pane_current_path}"
# Split horizontally, new pane below
bind -n M-h split-window -h -c "#{pane_current_path}"

# ZOOM INTO PANE

bind -n M-z resize-pane -Z

# RESIZE PANES

bind -n M-H resize-pane -L
bind -n M-L resize-pane -R
bind -n M-K resize-pane -U
bind -n M-J resize-pane -D

bind p command-prompt

bind -n M-w choose-window
bind -n M-s choose-session

bind -n M-b set-option status

# RELOAD CONFIG
bind r 'source-file "$HOME/.config/tmux/tmux.conf"; display "Tmux config reloaded!"'
