# Settings

set -g status-position top

# Set tmux in 24bit color
set-option -sa terminal-overrides ",xterm*:Tc"
#set -g default-terminal "screen-256color"

# SET LINE HISTORY LIMIT TO 10000
set -g history-limit 10000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# ENABLE MOUSE
set -g mouse on

set -s escape-time 0

# Longes session name to display properly
set -g status-left-length 20 # could be any number

# CHANGE PREFIX FROM CTRL-B TO CTRL-A
unbind C-b
set -g prefix M-a
#bind C-a send-prefix

## Use Vim keys for movement
setw -g mode-keys vi

# NUMBER WINDOWS STARTING FROM 1
set -g base-index 1
