# Address settings
bind_to_address 			"127.0.0.1"		# Run server on specified address	
port 									"6600"				# Run server on speified port

# Directories
music_directory				"~/music"											# Location of your music library
playlist_directory		"~/.config/mpd/playlists"			# Location of your playlists info
db_file								"~/.config/mpd/mpd.db"				# Location of MPD database file
log_file							"~/.config/mpd/logs"					# Location of MPD logs file
state_file						"~/.config/mpd/state"					# Location of MPD state file
sticker_file					"~/.config/mpd/sticker.sql"		# Location of MPD sticker file
auto_update						"yes" 												# Auto update music directory when new songs are added

# Setup audio output to pulseaudio
audio_output {
	type								"pulse"
	name								"pulse audio"
	device							"pulse"
	mixer_type					"hardware"
}

# Add visualizer
audio_output {
	type								"fifo"
	name								"my_fifo"
	path								"/tmp/mpd.fifo"
	format							"44100:16:2"
}

# This probably gonna be removed
#input {
#        plugin "curl"
#}
